site_name: DeepNet Wiki
site_url: https://macinsight.github.io
repo_url: https://github.com/macinsight/deepwiki
edit_uri: edit/main/docs/
theme:
  name: material
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  palette:
    scheme: slate
    primary: black
    accent: indigo
  features:
    - navigation.footer
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - toc.follow
    - content.action.edit
    - content.action.view
  icon:
    repo: fontawesome/brands/git-alt
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
plugins:
  - search
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/23Y2bZCtbP
      name: DeepNet Discord
  analytics:
    provider: google
    property: G-QT5ZVG7KT3

nav:
  - Home: index.md
  - Lore:
    - Index: lore/index.md
  - Modding: modding.md
  - Mechanics: mechanics/index.md
  - DeepAI: deepai.md
  - Community:
    - Contributing: community/contributing.md
    - About: community/index.md
    - Discord: community/discord.md
